# Generated by Django 5.1.6 on 2025-02-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_specialist_appointment_delete_booking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='total_price',
        ),
    ]
