# Generated by Django 5.1.6 on 2025-02-20 09:55

import django.db.models.deletion
import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='user',
            field=models.OneToOneField(blank=True, default=pages.models.get_default_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.CharField(choices=[('hairdresser', 'Hairdresser'), ('tattoo_artist', 'Tattoo Artist'), ('nail_technician', 'Nail Technician'), ('dog_groomer', 'Dog Groomer'), ('aesthetic_practitioner', 'Aesthetic Practitioner'), ('sports_therapist', 'Sports Therapist'), ('physiotherapist', 'Physiotherapist'), ('chiropractor', 'Chiropractor'), ('semi_permanent_makeup', 'Semi-Permanent Makeup Artist')], max_length=100),
        ),
    ]
