# Generated by Django 5.1.6 on 2025-02-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_specialist_user_alter_specialist_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
