# Generated by Django 5.1.6 on 2025-02-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contactus_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='department',
            field=models.CharField(choices=[('Beauticians', 'Beauticians'), ('Hairdressers', 'Hairdressers'), ('Nail Technicians', 'Nail Technicians'), ('barbers', 'Barbers'), ('Tattoo Artists', 'Tattoo Artists'), ('Dog Groomers', 'Dog Groomers'), ('Aesthetic Practitioners', 'Aesthetic Practitioners'), ('Sports Therapists', 'Sports Therapists'), ('Physiotherapists', 'Physiotherapists'), ('Chiropractors', 'Chiropractors'), ('Semi-Permanent Makeup Artists', 'Semi-Permanent Makeup Artists'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
