# Generated by Django 5.1.6 on 2025-02-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_contactus_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.CharField(choices=[('Beauticians', 'Beauticians'), ('hairdresser', 'Hairdresser'), ('tattoo_artist', 'Tattoo Artist'), ('nail_technician', 'Nail Technician'), ('dog_groomer', 'Dog Groomer'), ('aesthetic_practitioner', 'Aesthetic Practitioner'), ('sports_therapist', 'Sports Therapist'), ('physiotherapist', 'Physiotherapist'), ('chiropractor', 'Chiropractor'), ('semi_permanent_makeup', 'Semi-Permanent Makeup Artist')], max_length=100),
        ),
    ]
