# Generated by Django 5.1.6 on 2025-02-25 14:16

import django.db.models.deletion
import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_specialist_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='user',
            field=models.ForeignKey(blank=True, default=pages.models.get_default_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
