# Generated by Django 5.1.6 on 2025-02-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_specialist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='session_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=6),
        ),
    ]
