# Generated by Django 5.1.6 on 2025-02-27 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_appointment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
