# Generated by Django 5.1.6 on 2025-02-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_userprofile_reset_token_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
