# Generated by Django 5.1.6 on 2025-03-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(blank=True, choices=[('Beauticians', 'Beauticians'), ('Hairdressers', 'Hairdressers'), ('Nail Technicians', 'Nail Technicians'), ('Tattoo Artists', 'Tattoo Artists'), ('Dog Groomers', 'Dog Groomers'), ('Aesthetic Practitioners', 'Aesthetic Practitioners'), ('Sports Therapists', 'Sports Therapists'), ('Physiotherapists', 'Physiotherapists'), ('Chiropractors', 'Chiropractors'), ('Semi-Permanent Makeup Artists', 'Semi-Permanent Makeup Artists')], max_length=100, null=True),
        ),
    ]
